version: '3.1'
services:
  stats-server:
    build: ./stats
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6542:5431"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./ewm
    depends_on:
      - ewm-db
      - stats-server
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
